---
# tasks file for first-role

- name: Updating the server
  yum:
   name: '*'
   state: latest

- name: Installing fail2ban
  yum:
   name: fail2ban
   state: latest

- name: Enabling fail2ban from boot. 
  service:
   name: fail2ban
   state: started
   enabled: true
